package cmd

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

// initCmd scaffolds a starter folder containing the artefacts a fresh
// fleetsweeper deployment needs: Helm overrides, an example ClusterScan,
// and a README walking through the first install.
var initCmd = &cobra.Command{
	Use:   "init [path]",
	Short: "Scaffold a starter deployment folder",
	Long: "Create a folder containing values.yaml, a sample ClusterScan, and\n" +
		"a README explaining how to install Fleetsweeper from those files.\n" +
		"Run with no argument to scaffold into ./fleetsweeper-deploy.",
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	initCmd.Flags().Bool("force", false, "Overwrite existing files in the target folder.")
}

// runInit performs the scaffold.
func runInit(cmd *cobra.Command, args []string) error {
	dir := "fleetsweeper-deploy"
	if len(args) == 1 {
		dir = args[0]
	}
	force, _ := cmd.Flags().GetBool("force")

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %q: %w", dir, err)
	}

	files := map[string]string{
		"values.yaml":        renderStarterValues(starterToken()),
		"clusterscan.yaml":   starterClusterScan,
		"serve-config.yaml":  starterServeConfig,
		"README.md":          starterReadme,
	}

	for name, body := range files {
		path := filepath.Join(dir, name)
		if _, err := os.Stat(path); err == nil && !force {
			return fmt.Errorf("%q exists; pass --force to overwrite", path)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %q: %w", path, err)
		}
	}

	fmt.Fprintf(cmd.ErrOrStderr(), "scaffolded %s\n", dir)
	fmt.Fprintf(cmd.ErrOrStderr(), "  next: cd %s && cat README.md\n", dir)
	return nil
}

// starterToken returns a fresh hex-encoded 32-byte random value the README
// suggests as the bootstrap admin token. Generated at scaffold time so the
// user does not have to invent one.
func starterToken() string {
	var buf [32]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "CHANGE_ME_BEFORE_INSTALL"
	}
	return hex.EncodeToString(buf[:])
}

// renderStarterValues fills the values template with the freshly-minted
// bootstrap token.
func renderStarterValues(token string) string {
	return fmt.Sprintf(starterValuesTemplate, token)
}

// starterValuesTemplate is the values.yaml the init command writes. It
// covers the 90% deployment shape: single-replica SQLite with auth, the
// controller enabled, and CRDs installed by the chart.
const starterValuesTemplate = `# Generated by ` + "`fleetsweeper init`" + `. Edit freely; the chart accepts every
# key documented at deploy/helm/fleetsweeper/values.yaml in the project repo.

replicaCount: 1

auth:
  # Bootstrap admin token. Treat it as a long-term emergency credential and
  # mint scoped operator keys for day-to-day use via:
  #   fleetsweeper apikey create --role operator --scope group:prod
  token: %q
  insecure: false

cors:
  # Add the dashboard's external origin once you put it behind an ingress.
  origins: []

scheduler:
  interval: 30m
  allContexts: true

persistence:
  enabled: true
  size: 5Gi

controller:
  enabled: true
  namespace: ""

crds:
  install: true

podDisruptionBudget:
  enabled: false

serviceMonitor:
  # Set to true if Prometheus Operator is installed.
  enabled: false

networkPolicy:
  # Set to true to default-deny with explicit allow rules.
  enabled: false
`

// starterClusterScan is the sample ClusterScan the init command writes.
const starterClusterScan = `# Apply once the CRD is installed (the chart installs it when crds.install=true):
#   kubectl apply -f clusterscan.yaml
#
# The controller reconciles every interval and triggers a scan whenever the
# resource's interval has elapsed. Check ` + "`kubectl get clusterscan -A`" + ` to see
# live phase, score, grade, and finding counts.
---
apiVersion: fleetsweeper.io/v1alpha1
kind: ClusterScan
metadata:
  name: starter
  namespace: fleetsweeper
spec:
  interval: 30m
  contexts:
    - replace-me-with-a-real-context
  emit:
    fleetDriftReport: true
`

// starterServeConfig is a starter for operators who prefer a config file
// over many CLI flags.
const starterServeConfig = `# Optional. Mount as /etc/fleetsweeper/serve.yaml and pass --config to use.
# Values can also be overridden by CLI flags or env vars.

addr: ":8080"
admin-addr: "127.0.0.1:8081"
db: "/data/fleet.db"
controller: true
scan-interval: "30m"
all-contexts: true
audit-retention: "720h"
`

// starterReadme is the post-scaffold walkthrough.
const starterReadme = `# Fleetsweeper starter

This folder was generated by ` + "`fleetsweeper init`" + ` and contains the four
artefacts a fresh deployment needs:

- ` + "`values.yaml`" + ` — Helm overrides for the bundled chart.
- ` + "`clusterscan.yaml`" + ` — a sample ClusterScan resource the operator
  reconciles into scheduled scans.
- ` + "`serve-config.yaml`" + ` — optional config file for non-Helm invocations.
- ` + "`README.md`" + ` — this file.

## Install

` + "```shell" + `
helm install fleetsweeper \
  oci://ghcr.io/dcadolph/fleetsweeper/chart \
  --namespace fleetsweeper --create-namespace \
  --values values.yaml

kubectl apply -f clusterscan.yaml
` + "```" + `

The bootstrap admin token is in ` + "`values.yaml`" + ` and is generated fresh on every
` + "`init`" + `. Treat it as long-term emergency access; mint scoped keys for
pipelines:

` + "```shell" + `
TOKEN=$(kubectl --namespace fleetsweeper get secret fleetsweeper-auth \
  -o jsonpath='{.data.token}' | base64 -d)

curl -X POST -H "Authorization: Bearer $TOKEN" \
  -H 'Content-Type: application/json' \
  -d '{"name":"ci-runner","role":"operator","cluster_scope":["group:prod"],"ttl":"720h"}' \
  http://localhost:8080/api/admin/keys
` + "```" + `

## Verify

` + "```shell" + `
kubectl get clusterscan -A         # phase, score, grade, lastScanTime
kubectl --namespace fleetsweeper port-forward svc/fleetsweeper 8080:8080
# Then open http://localhost:8080
` + "```" + `

## Next

- Adjust ` + "`spec.contexts`" + ` in ` + "`clusterscan.yaml`" + ` to your real cluster names.
- Set ` + "`scheduler.interval`" + ` in ` + "`values.yaml`" + ` for non-CRD scheduled scans, or
  delete it if you only want declarative scans.
- Read https://github.com/dcadolph/fleetsweeper/blob/main/docs/operator/overview.md
  for the operator design.
`
