{{- if .Values.auth.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
{{- if and (eq .Values.database.driver "postgres") .Values.database.postgres.dsn (not .Values.database.postgres.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  dsn: {{ .Values.database.postgres.dsn | quote }}
{{- end }}
{{- if and .Values.oidc.enabled (not .Values.oidc.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oidc
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client-secret: {{ .Values.oidc.clientSecret | quote }}
  session-secret: {{ .Values.oidc.sessionSecret | quote }}
{{- end }}
